import './sass/entry.scss';
import './sass/noJsStyle.scss'
import './polyfills/ie-touch';
import './navigation/initialProjectsSetup';
import './navigation/changePage';
import './navigation/changeProject';
import './navigation/hideShowMenu';
import './navigation/resizeMenu';
import './headerEffect/headerEffect';
import './eventHandlers/mouseWheelHandler';
import './eventHandlers/mouseMoveHandler';
import './eventHandlers/keyDownHandler';
import './eventHandlers/touchHandler';
import './eventHandlers/resizeHandler';
import './eventHandlers/menuItemClick';